### ISSUE TITLE
bang methods persist ActiveRecord models even if the AR model after_save raises some errors

### ISSUE THREAD

**Issue by robbiegill** [aasm/aasm#243]
Scenario: An ActiveRecord model has an after_save callback that can raise errors. When calling save on such a model, the transaction will be rolled back and the updates not persisted in the database. 

Problem: Using an aasm bang method to induce the save will persist the changes.

In the following spec, raising `ActiveRecord::Rollback` or `ActiveRecord::RecordInvalid` in the doom model's `after_save` callback does not rollback the transaction and still executes the AR model's `after_commit` callback (`test_after_commit` gem needed to see this in test env). The `run!` method correctly returns false, but the transaction setting `aasm_state` to running will not be rolled back. 

Note: if the `after_save` raises `StandardError`, the transaction _is_ rolled back.

```ruby
class Doom < ActiveRecord::Base
  include AASM

  after_save :mock_after_save_hook
  after_commit :mock_after_commit_hook

  def mock_after_save_hook
  end

  def mock_after_commit_hook
  end

  aasm do
    state :sleeping, initial: true
    state :running

    event :run do
      transitions from: :sleeping, to: :running
    end
  end
end

RSpec.describe Doom, type: :model do
  let!(:doom) { described_class.create! }

  before do
    expect(doom).to receive(:mock_after_save_hook).and_raise(error)
  end

  shared_examples_for 'it does not write to the database' do
    it do
      doom.run! rescue nil
      doom.reload
      expect(doom.sleeping?).to be_truthy
    end
  end

  shared_examples_for 'it does not run an after commit' do
    it do
      expect(doom).to_not receive(:mock_after_commit_hook)
      doom.run! rescue nil
    end
  end

  context 'StandardError' do
    let(:error) { StandardError }
    it_behaves_like 'it does not write to the database'
    it_behaves_like 'it does not run an after commit'
  end

  context 'ActiveRecord::Rollback' do
    let(:error) { ActiveRecord::Rollback }
    it_behaves_like 'it does not write to the database'
    it_behaves_like 'it does not run an after commit'
  end

  context 'ActiveRecord::RecordInvalid' do
    let(:error) { ActiveRecord::RecordInvalid.new doom }
    it_behaves_like 'it does not write to the database'
    it_behaves_like 'it does not run an after commit'
  end
end
``` 

```
Doom
  StandardError
    behaves like it does not write to the database
      should be truthy
    behaves like it does not run an after commit
      should not #<RSpec::Mocks::Matchers::Receive:0x007fe3b54ad008>
  ActiveRecord::Rollback
    behaves like it does not write to the database
      should be truthy (FAILED - 1)
    behaves like it does not run an after commit
      should not #<RSpec::Mocks::Matchers::Receive:0x007fe3b552dca8> (FAILED - 2)
  ActiveRecord::RecordInvalid
    behaves like it does not write to the database
      should be truthy (FAILED - 3)
    behaves like it does not run an after commit
      should not #<RSpec::Mocks::Matchers::Receive:0x007fe3b56a40f0> (FAILED - 4)

Failures:

  1) Doom ActiveRecord::Rollback behaves like it does not write to the database should be truthy
     Failure/Error: expect(doom.sleeping?).to be_truthy
       expected: truthy value
            got: false
     Shared Example Group: "it does not write to the database" called from ./spec/models/doom_spec.rb:33
     # ./spec/models/doom_spec.rb:14:in `block (3 levels) in <top (required)>'

  2) Doom ActiveRecord::Rollback behaves like it does not run an after commit should not #<RSpec::Mocks::Matchers::Receive:0x007fe3b552dca8>
     Failure/Error: doom.run! rescue nil
       (#<Doom:0x007fe3b54fef70>).mock_after_commit_hook(no args)
           expected: 0 times with any arguments
           received: 1 time
     Shared Example Group: "it does not run an after commit" called from ./spec/models/doom_spec.rb:34
     # ./spec/models/doom_spec.rb:21:in `block (3 levels) in <top (required)>'

  3) Doom ActiveRecord::RecordInvalid behaves like it does not write to the database should be truthy
     Failure/Error: expect(doom.sleeping?).to be_truthy
       expected: truthy value
            got: false
     Shared Example Group: "it does not write to the database" called from ./spec/models/doom_spec.rb:39
     # ./spec/models/doom_spec.rb:14:in `block (3 levels) in <top (required)>'

  4) Doom ActiveRecord::RecordInvalid behaves like it does not run an after commit should not #<RSpec::Mocks::Matchers::Receive:0x007fe3b56a40f0>
     Failure/Error: doom.run! rescue nil
       (#<Doom:0x007fe3b56b7970>).mock_after_commit_hook(no args)
           expected: 0 times with any arguments
           received: 1 time
     Shared Example Group: "it does not run an after commit" called from ./spec/models/doom_spec.rb:40
     # ./spec/models/doom_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.09274 seconds (files took 1.61 seconds to load)
6 examples, 4 failures
```

**Comment by igorbelo** [comment]
It seems that `aasm` creates its own transaction events are called with bang.
[See this line](https://github.com/aasm/aasm/blob/44a17aa5357d60e20cbd1a5da4a27063e113ffa2/lib/aasm/persistence/active_record_persistence.rb#L175)

aasm transaction is the most external transaction and your callback is at the most internal transaction, so what happens when you raise an `ActiveRecord::Rollback` inside your most internal transaction? nothing, because it won't propagate up...

It's like:
```ruby
Model.transaction do
  #aasm persistence
  Model.transaction do
    raise ActiveRecord::Rollback
  end
end
```

`aasm` will persist the transition even if your `after_save` raises `ActiveRecord::Rollback`, `ActiveRecord::RecordInvalid` or anything...

**Comment by robbiegill** [comment]
Yes, that is how aasm's implementation works, but the outcome is _very_ undesirable.

In the simplest ActiveRecord case, `model.next_state!` should be equivalent to `model.aasm_state = 'next_state'; model.save`. With the exception described above, both will return false, but one will persist and the other will not.

**Comment by alto** [comment]
@robbiegill I will come back to that issue as soon as possible. First I want to get support for multiple state machines in one class out of the door (see #158).

**Comment by zhangsoledad** [comment]
you can set `config.requires_new_transaction` true,
it will be
```ruby
 Model.transaction do
  #aasm persistence
  Model.transaction(:requires_new => true) do
    raise ActiveRecord::Rollback
  end
end
```
this will work with nested transactions

**Comment by rringler** [comment]
:+1: on bang methods calling `#save!`

**Comment by misham** [comment]
Did anything ever happen with this?

Using database_cleaner gem with `transaction` strategy causes tests to fail due to the transaction "wrapping".
