### ISSUE TITLE
Event names ending in `!` raising exception

### ISSUE THREAD

**Issue by carvil** [aasm/aasm#303]
Hi there,

When I've tried to upgrade `aasm` from `4.2.0` to `4.5.2`, I noticed an exception being raised when event names end in `!`. 

As an example, if you run this code with the new version:

```
require 'aasm'

class Job
  include AASM
  aasm do
    state :sleeping, initial: true
    state :running

    event :run! do
      transitions from: :sleeping, to: :running
    end
  end
end

job = Job.new
job.run!
```

You will see the following exception:

```
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/base.rb:95:in `class_eval': /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/base.rb:96: syntax error, unexpected '?', expecting ';' or '\n' (SyntaxError)
        def may_run!?(*args)
                     ^
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/base.rb:96: syntax error, unexpected '\n', expecting '='
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/base.rb:98: syntax error, unexpected keyword_end, expecting end-of-input
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/base.rb:95:in `event'
        from test.rb:9:in `block in <class:Job>'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/aasm.rb:56:in `instance_eval'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.5.2/lib/aasm/aasm.rb:56:in `aasm'
        from test.rb:5:in `<class:Job>'
        from test.rb:3:in `<main>'
```

Apologies if I missed an upgrade note somewhere, but I couldn't find it.
Is this something you won't support going forward?

Thanks

**Comment by alto** [comment]
@carvil I'm surprised it worked in the past (for versions `<= 4.2.0`). Are you sure? _AASM_ generates those `run!` by itself (as the behavior is different when using `run` or `run!`.

**Comment by carvil** [comment]
That is correct @alto , it works under version `4.2.0` (we have this live) but not under the latest versions. Here is a transcript of what I did:

```
~/aasm_test » gem list | grep aasm
~/aasm_test » gem install aasm -v 4.2.0
Fetching: aasm-4.2.0.gem (100%)
Successfully installed aasm-4.2.0
1 gem installed
~/aasm_test » gem list | grep aasm                                                                 
aasm (4.2.0)
~/aasm_test » ruby test.rb
~/aasm_test » gem uninstall aasm  
Successfully uninstalled aasm-4.2.0
~/aasm_test » gem list | grep aasm 
~/aasm_test » gem install aasm -v 4.7.0  
Fetching: aasm-4.7.0.gem (100%)
Successfully installed aasm-4.7.0
1 gem installed
~/aasm_test » gem list | grep aasm 
aasm (4.7.0)
~/aasm_test » ruby test.rb   
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/base.rb:95:in `class_eval': /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/base.rb:96: syntax error, unexpected '?', expecting ';' or '\n' (SyntaxError)
        def may_run!?(*args)
                     ^
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/base.rb:96: syntax error, unexpected '\n', expecting '='
/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/base.rb:98: syntax error, unexpected keyword_end, expecting end-of-input
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/base.rb:95:in `event'
        from test.rb:9:in `block in <class:Job>'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/aasm.rb:56:in `instance_eval'
        from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/aasm-4.7.0/lib/aasm/aasm.rb:56:in `aasm'
        from test.rb:5:in `<class:Job>'
        from test.rb:3:in `<main>'
~/aasm_test » ```

**Comment by anilmaurya** [comment]
@alto It was working for earlier version because you were defining `may_{name}?` using `define_method` syntax. Now you are using `class_eval` for defining `may_{name}?`.

https://github.com/aasm/aasm/commit/eca394bb9bff36426d0a5e238674d878ef2c4351#diff-b8d4c2d34e62d1889f6296e352014c10L79

In this particular scenario aasm is trying to define method `may_run!?` which is invalid method name because characters !, ? and = can only appear at the end (http://stackoverflow.com/a/10542599/1970061) .

`define_method` is not raising error (according to me, it should). I have file this issue on ruby bug tacker https://bugs.ruby-lang.org/issues/11983 .

**Comment by anilmaurya** [comment]
According to Ruby Community

```
It's a spec that define_method can define any name and __send__ also can call it.
```

@alto Now we have two options:
1. Use `define_method` instead of `class_eval` for defining methods.
2. Update docs mentioning not to use event name with bangs.

What do you prefer ?

**Comment by pirj** [comment]
@carvil, the bug seems to be resolved on master (4.9.2)
Please confirm that the behaviour is as expected.

**Comment by carvil** [comment]
Thanks, @pirj, it works now as expected.

**Comment by anilmaurya** [comment]
Thank you @carvil for reporting this bug.

Closing this issue, now AASM is using `define_method` (https://github.com/aasm/aasm/blob/master/lib/aasm/base.rb#L214) .
