### ISSUE TITLE
NoMethodError - undefined method `statuses' for #<Class:0x0000000ad23778>

### ISSUE THREAD

**Issue by jack-nie** [aasm/aasm#305]
Hi there,
   When I've tried to config custom column for aasm state, I get the following error:
```
NoMethodError - undefined method `statuses' for #<Class:0x0000000ad23778>:
  activerecord (4.1.0) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:126:in `aasm_raw_attribute_value'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:120:in `aasm_write_attribute'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:81:in `aasm_write_state_without_persistence'
  aasm (4.7.0) lib/aasm/instance_base.rb:16:in `current_state='
  aasm (4.7.0) lib/aasm/instance_base.rb:26:in `enter_initial_state'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:150:in `block in aasm_ensure_initial_state'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:146:in `aasm_ensure_initial_state'
  aasm (4.7.0) lib/aasm/persistence/active_record_persistence.rb:36:in `block in included'
  activesupport (4.1.0) lib/active_support/callbacks.rb:438:in `block in make_lambda'
  activesupport (4.1.0) lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.0) lib/active_record/core.rb:201:in `initialize'
```

Here is my code:
```
 aasm column: :status do
    state :waiting, initial: true
    state :confirmed
    state :cancelled
    state :paid
    state :refunding
    state :refunded

    event :confirm do
      transitions from: :waiting, to: :confirmed
    end

    event :cancel do
      transitions from: [:confirmed, :waiting], to: :cancelled
    end
    .....
end
```
I'm using it with `enumerize`.

**Comment by alto** [comment]
@jack-nie From reading a bit on the [enumerize github page](https://github.com/brainspec/enumerize), it has nothing to do with _ActiveRecord_'s [enumerations](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html). Unfortunately, _AASM_ only supports Rails enumerations.

**Comment by sebastian-miclea** [comment]
Hi,

I just set up a new rails project and added aasm, but started getting this same error.
I just have to`include AASM` in the model, and start getting this error when trying to access the model. I don't have [enumerize], just an empty Rails `5.1.4` app.

Any ideas to get passed this error?

Thanks,

**Comment by ankurshukla1993** [comment]
Can somebody please explain this issue.
I am facing this issue from past many days.

**Comment by longboardcat** [comment]
Is your status column a string?
