### ISSUE TITLE
Rspec ArgumentError when passing parameters to event

### ISSUE THREAD

**Issue by joerodrig3** [aasm/aasm#394]
I'm running into an issue where passing parameters into an AASM event from my controller produces an argument error. 

The error is produced from the example code below:
```ruby
  # controllers/records_controller.rb
  def run
    @record.start_running!(current_user)
  end

  # controllers/records_controller_spec.rb
  describe "#run" do
    ...
    it "begins running a pending record" do
      put project_record_run_url(project, subject)
      expect(response).to have_http_status(:success)
    end
  end

  # models/record.rb
  event :start_running, after: proc { |*args| run_record(*args) } do
    transitions from: :pending, to: :running
  end


  def run_record(user)
    update(user: user, start_time: Time.current)
  end
```

Error produced:
```ruby
Failure/Error: @record.start_running!(current_user)
     
     ArgumentError:
       Wrong number of arguments. Expected 0, got 1.
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:156:in `invoke_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `block in invoke_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `each'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `invoke_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `block in invoke_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `each'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:165:in `invoke_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/core/event.rb:57:in `fire_global_callbacks'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/aasm.rb:171:in `aasm_fired'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/aasm.rb:120:in `aasm_fire_event'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/persistence/active_record_persistence.rb:194:in `block in aasm_fire_event'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/persistence/active_record_persistence.rb:192:in `aasm_fire_event'
     # /Users/Joe/.gem/ruby/2.3.1/gems/aasm-4.11.0/lib/aasm/base.rb:126:in `block in event'
     # ./app/controllers/records_controller.rb:33:in `run'
     # /Users/Joe/.gem/ruby/2.3.1/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
     # /Users/Joe/.gem/ruby/2.3.1/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/Joe/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/sentry-raven-1.2.2/lib/raven/integrations/rack.rb:50:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/Joe/.gem/ruby/2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
     # ./spec/requests/builds_controller_spec.rb:64:in `block (7 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:9:in `block (3 levels) in <top (required)>'
     # /Users/Joe/.gem/ruby/2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/Joe/.gem/ruby/2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/Joe/.gem/ruby/2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/Joe/.gem/ruby/2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:8:in `block (2 levels) in <top (required)>'
```

I've checked through the [parameterized event code](https://github.com/aasm/aasm/blob/master/spec/models/parametrised_event_multiple.rb#L16) and the accompanying [specs](https://github.com/aasm/aasm/blob/master/spec/unit/event_spec.rb#L350). I've also looked through some more recent solutions given in issue #324, but can't seem to figure out why this error is being produced. I'm able to enter the `run_record` method just fine, but it isn't until that method returns that this error is produced.

Oddly enough, this issue also seems to only occur in RSpec. Manually running the code recognizes the call just fine.

**Comment by joerodrig3** [comment]
I've been able to work around this issue by doing:
```ruby
  # RSpec doesn't cooperate with passing parameters to AASM events. This method
  # works around that.
  def run_record(user)
    start_record(user)
    start_running!
  end

  def start_Record(user)
    update(user: user, start_time: Time.current)
  end
```

I'm still unsure why RSpec isn't working with the original code though

**Comment by joerodrig3** [comment]
It turns out the missing piece to this puzzle was that we had another event in our model:
```ruby
  after_all_events [:update_github_status]
```

The `update_github_status` event doesn't expect any parameters to be passed in, so that was causing the error above. 
I was able to resolve this by just doing:

```ruby
def update_github_status(_user = nil)
  ...
end
```
