### ISSUE TITLE
Getting "wrong number of arguments (given 2, expected 1)" error, when using active record boolean check method as guard

### ISSUE THREAD

**Issue by PragmaticEd** [aasm/aasm#416]
Getting this error:

```
wrong number of arguments (given 2, expected 1)
```

When executing an event, when using active record boolean check method as guard.
For example, i have `boolean` field in database, called `vip`.
Active record provides method `vip?`, that works fine everywhere, except, if you pass it as guard method:

```
# code that doesn't work
aasm :state do
  event(:pay)  {
    transitions(from: :finished, 
                     to: :paid,
                     after: [:handle_payment],
                     guards: [:vip?]
  )}
end

private

def handle_payment(argument)
end

```

Can be solved by making new private method, that does the check, like so:

```
# code that works
aasm :state do
  event(:pay)  {
    transitions(from: :finished, 
                     to: :paid,
                     after: [:handle_payment],
                     guards: [:is_vip?]
  )}
end

private

def handle_payment(argument)
end

def is_vip?
  self.vip?
end
```

But, i'm guessing, this is a bug, right?

I have to note, this error only occurres, if there is an `after` method that accepts an attribute:

```
@order.pay!(nil, "some value")
```

If the method `handle_payment` wouldn't accept arguments, then everything works fine.

ruby: `2.3.0p0`
rails: `5.0.0`
os:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by mvz** [comment]
I can confirm this with aasm 4.12.0 (I haven't checked the bit about having an `after` method with arguments). Using the attribute method without the `?` directly is also a good work-around (in this case, that would be `guard [:vip]`).

**Comment by project-eutopia** [comment]
I ran into the same problem trying to upgrade to version 4.12.  I was able to isolate this as a problem with how `aasm` seems to be handling guard methods that have variable arguments.  The boolean check methods like `vip?` have arity -1 (variable) but when `aasm` uses it as a guard it passes along a single argument, `nil`.  Here is some sample code that isolates the problem of a variable argument guard method receiving an extraneous `nil` argument:

```ruby
require "aasm"

class Foo
  include AASM

  aasm do
    state :null, initial: true
    state :alpha
    state :beta

    event :make_alpha do
      transitions from: :null, to: :alpha, if: :check?
    end

    event :make_beta do
      transitions from: :null, to: :beta, if: :good?
    end
  end

  def check?
    true
  end

  def good?(*args)
    raise ArgumentError.new("Should receive no arguments, received #{args.inspect}") unless args.count == 0
    true
  end
end

# No problem
Foo.new.tap do |foo|
  foo.make_alpha
end

# FIXME: Passes on bad arguments!
Foo.new.tap do |foo|
  foo.make_beta
end
```

This fails for me (ruby 2.4.1, aasm 4.12.0) with the following error.
```
aasm.rb:25:in `good?': Should receive no arguments, received [nil] (ArgumentError)
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:72:in `invoke_callbacks_compatible_with_guard'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `block in invoke_callbacks_compatible_with_guard'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `each'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `all?'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:116:in `invoke_callbacks_compatible_with_guard'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/transition.rb:41:in `allowed?'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/event.rb:143:in `block in _fire'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/event.rb:140:in `each'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/event.rb:140:in `_fire'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/core/event.rb:44:in `may_fire?'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/aasm.rb:113:in `aasm_fire_event'
	from /home/chris/.rvm/gems/ruby-2.4.1/gems/aasm-4.12.0/lib/aasm/base.rb:131:in `block in event'
	from aasm.rb:37:in `block in <main>'
	from aasm.rb:36:in `tap'
	from aasm.rb:36:in `<main>'
```

**Comment by anilmaurya** [comment]
Hi @project-eutopia ,

Thank you for your investigation, I think this issue is related to https://github.com/aasm/aasm/commit/c3b6454e8e9ca499e57aac4c74ec18bf9fa028b4

I will investigate further soon.

**Comment by arialblack14** [comment]
Hello all,
I have an `4.2.3` app with `gem 'aasm', '~> 4.12.2'`.

On my model I have this event:
```
event :approve do
      before do
        log("Notifying submitter...")
      end

      transitions :from => :submitted, :to => :approved
end
```
I get the error 
`wrong number of arguments (1 for 0)`
which disappears if I remove the before block.
