### ISSUE TITLE
Generator creates migrations in rails 5 format incompatible with rails 4

### ISSUE THREAD

**Issue by prog1dev** [aasm/aasm#515]
Environment:
rails -v ```Rails 4.1.8```
ruby -v ```ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin15.0]```
aasm -v ```4.12.3```

Command `rails generate aasm qwe` works fine, but after that on `rake db:migrate` `NoMethodError` raises:
```
$ rake db:migrate                                                                
-- [](4.1)
-- [](4.1)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x007f82a11daaf8>
/Users/ivan.filenko/projects/cms/db/migrate/20171213131513_aasm_create_qwes.rb:1:in `<top (required)>'
/Users/ivan.filenko/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
/Users/ivan.filenko/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x007f82a11daaf8>
/Users/ivan.filenko/projects/cms/db/migrate/20171213131513_aasm_create_qwes.rb:1:in `<top (required)>'
/Users/ivan.filenko/.rbenv/versions/2.1.5/bin/bundle:23:in `load'
/Users/ivan.filenko/.rbenv/versions/2.1.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by timlawrenz** [comment]
@prog1dev With Rails 4 being deprecated, can this issue be closed?

**Comment by anilmaurya** [comment]
@timlawrenz Thank you for pointing out.
