### ISSUE TITLE
unless is wrongly blamed for failure in exception

### ISSUE THREAD

**Issue by BrianHicks** [aasm/aasm#544]
I have reproduced the following minimal state machine:

```ruby
class Machine
  include AASM

  aasm do
    state :open, default: true
    state :closed

    event :close, unless: :some_validation do
      transitions from: :open, to: :closed
    end
  end

  def some_validation pass_through
    pass_through
  end
end
```

It works fine when you work with it normally:

```text
[1] pry(main)> machine = Machine.new
=> #<Machine:0x007fb6998bcc78>
[2] pry(main)> machine.open?
=> true
[3] pry(main)> machine.closed?
=> false
[4] pry(main)> machine.close true
AASM::InvalidTransition: Event 'close' cannot transition from 'open'.
from /Users/brian/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:199:in `aasm_failed'
[5] pry(main)> machine.close false
=> true
```

but when you try to close it, and it's already closed, it blames `:some_validation` for the failure regardless of the output of `#some_validation`:

```text
[6] pry(main)> machine.may_close? false
=> false
[7] pry(main)> machine.close false
AASM::InvalidTransition: Event 'close' cannot transition from 'closed'. Failed callback(s): [:some_validation].
from /Users/brian/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:199:in `aasm_failed'
[8] pry(main)> machine.close true
AASM::InvalidTransition: Event 'close' cannot transition from 'closed'. Failed callback(s): [:some_validation].
from /Users/brian/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/aasm-4.12.3/lib/aasm/aasm.rb:199:in `aasm_failed'
```

Any idea how I can clarify this? I'd like to send these validation names to the frontend, but I can't trust them right now.

**Comment by BrianHicks** [comment]
also, I would have expect to see this validation on line 4 of the REPL. Seems like something may just be backwards somewhere?
