### ISSUE TITLE
transaction rollback question

### ISSUE THREAD

**Issue by icbd** [aasm/aasm#575]
if i want to rollback all transaction when raise a exception, what should i do?

i use this code, when run `Article.last.publish`, the new article will be created yet. i hope the raise can rollback the creation of the new article.

thanks!

```ruby
module ArticleAasm
  extend ActiveSupport::Concern
  included do
    include AASM

    aasm requires_new_transaction: false do
      state :init, :initial => true

      state :showing,
            before_enter: Proc.new {
              puts ">>>before_enter"
              Article.create(title: "new article #{rand(100)}before publish")
            },
            after_enter: Proc.new {
              puts ">>>after_enter"
              raise "!!!"
            }

      event :publish do
        transitions from: :init, to: :showing
      end
    end
  end
end
```

**Comment by anuja-joshi** [comment]
@icbd transition and `before_enter` and `after_enter` callbacks are done under a transaction. So, if there is exception in `after_enter` it will definitely rollback changes and so the creation of Article. Please recheck this, if issue still persist then let us know the details - gem version, db etc.

**Comment by timlawrenz** [comment]
Hey @icbd, is this still an issue?

**Comment by icbd** [comment]
> Hey @icbd, is this still an issue?

```
2.6.3 :001 > Article.create(title:'123').publish
   (0.4ms)  SELECT sqlite_version(*)
   (0.0ms)  begin transaction
  Article Create (0.4ms)  INSERT INTO "articles" ("title", "aasm_state", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "123"], ["aasm_state", "init"], ["created_at", "2020-12-12 02:44:49.216196"], ["updated_at", "2020-12-12 02:44:49.216196"]]
   (0.9ms)  commit transaction
>>>before_enter
   (0.0ms)  begin transaction
  Article Create (0.3ms)  INSERT INTO "articles" ("title", "aasm_state", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "new article 26before publish"], ["aasm_state", "init"], ["created_at", "2020-12-12 02:44:49.221388"], ["updated_at", "2020-12-12 02:44:49.221388"]]
   (0.6ms)  commit transaction
>>>after_enter
Traceback (most recent call last):
        2: from (irb):1
        1: from app/models/article.rb:14:in `block (2 levels) in <class:Article>'
RuntimeError (!!!)
```

```
Article.create(title:'123').publish!
   (0.1ms)  begin transaction
  Article Create (0.4ms)  INSERT INTO "articles" ("title", "aasm_state", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "123"], ["aasm_state", "init"], ["created_at", "2020-12-12 02:45:24.532628"], ["updated_at", "2020-12-12 02:45:24.532628"]]
   (1.0ms)  commit transaction
>>>before_enter
   (0.0ms)  begin transaction
  Article Create (0.3ms)  INSERT INTO "articles" ("title", "aasm_state", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["title", "new article 50before publish"], ["aasm_state", "init"], ["created_at", "2020-12-12 02:45:24.535449"], ["updated_at", "2020-12-12 02:45:24.535449"]]
  Article Update (0.1ms)  UPDATE "articles" SET "aasm_state" = ?, "updated_at" = ? WHERE "articles"."id" = ?  [["aasm_state", "showing"], ["updated_at", "2020-12-12 02:45:24.536483"], ["id", 3]]
>>>after_enter
   (0.4ms)  rollback transaction
Traceback (most recent call last):
        3: from (irb):4
        2: from (irb):4:in `rescue in irb_binding'
        1: from app/models/article.rb:14:in `block (2 levels) in <class:Article>'
RuntimeError (!!!)
```

we should use bang method
