### ISSUE TITLE
Cannot transition from obvious state change?

### ISSUE THREAD

**Issue by slhck** [aasm/aasm#654]
**Describe the bug**

I have a very simple state change that AASM fails to transition with.

**To Reproduce**

```ruby
class TestAasm
  include AASM
  aasm do
    state :undefined, initial: true
    state :initial_loading
    state :playing

    event :evt_stalling do
      transitions from: :undefined, to: :initial_loading
    end
    event :evt_playing do
      transitions from: :initial_loading, to: :playing
    end
    event :evt_playing do
      transitions from: :undefined, to: :playing
    end
  end
end

RSpec.describe 'TestAasm' do
  it "transitions correctly" do
    sm = TestAasm.new
    expect(sm.undefined?).to be(true)
    sm.evt_stalling
    expect(sm.initial_loading?).to be(true)
    sm.evt_playing
    expect(sm.playing?).to be(true)
  end
end
```

**Expected behavior**

I expect the test to pass. The stalling event should put the state into initial loading (correct), and then the playing event should change the state to "playing".

**Actual behavior**

The test fails with:

```
W, [2019-11-18T09:28:37.636019 #915]  WARN -- : TestAasm: overriding method 'may_evt_playing?'!
W, [2019-11-18T09:28:37.636071 #915]  WARN -- : TestAasm: overriding method 'evt_playing!'!
W, [2019-11-18T09:28:37.636084 #915]  WARN -- : TestAasm: overriding method 'evt_playing'!
W, [2019-11-18T09:28:37.636097 #915]  WARN -- : TestAasm: overriding method 'evt_playing_without_validation!'!
F

Failures:

  1) TestAasm transitions correctly
     Failure/Error: sm.evt_playing
     
     AASM::InvalidTransition:
       Event 'evt_playing' cannot transition from 'initial_loading'.
     # /usr/local/bundle/gems/aasm-5.0.6/lib/aasm/aasm.rb:202:in `aasm_failed'
     # /usr/local/bundle/gems/aasm-5.0.6/lib/aasm/aasm.rb:112:in `aasm_fire_event'
     # /usr/local/bundle/gems/aasm-5.0.6/lib/aasm/base.rb:135:in `block in event'
     # ./spec/lib/aasm_spec.rb:26:in `block (2 levels) in <main>'
     # /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
     # /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
     # /usr/local/bundle/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'
```

**Additional context**

AASM 5.0.6 with Ruby 2.6.5

**Comment by slhck** [comment]
Oh, I understand now. You cannot pass duplicate blocks for the same event, yet different state changes. I came from Python [transitions](https://github.com/pytransitions/transitions#transitions) where this is possible.
