### ISSUE TITLE
Calling `.empty?` for `nil` from `aasm_ensure_initial_state` with Mongoid

### ISSUE THREAD

**Issue by zedtux** [aasm/aasm#793]
**Describe the bug**
Since the commit [1c5117](https://github.com/aasm/aasm/commit/1c5117720c4115789f52bac3768b6e9ec7d9fc44), and starting with AASM version 5.0.5, AASM is no more compatible with Mongoid aliased fields.

You can find a code example from #535 which makes AASM breaking with :

```
      NoMethodError:
        undefined method `empty?' for nil:NilClass
      # /usr/local/bundle/gems/aasm-5.0.5/lib/aasm/persistence/mongoid_persistence.rb:109:in `block in aasm_ensure_initial_state'
      # /usr/local/bundle/gems/aasm-5.0.5/lib/aasm/persistence/mongoid_persistence.rb:103:in `each'
      # /usr/local/bundle/gems/aasm-5.0.5/lib/aasm/persistence/mongoid_persistence.rb:103:in `aasm_ensure_initial_state'
      # /usr/local/bundle/gems/mongoid-7.5.1/lib/mongoid/interceptable.rb:122:in `run_callbacks'
      # /usr/local/bundle/gems/mongoid-7.5.1/lib/mongoid/document.rb:116:in `block in initialize'
      # ...
```

**To Reproduce**
1. Create a model using a Mongoid aliased field like in #535
2. Try to call `.new` on it
3. See error

**Expected behavior**
The model initialization should work without any errors.

**Comment by bk-one** [comment]
+1
