### ISSUE TITLE
breaking change in 5.5.0 with literal_invoker

### ISSUE THREAD

**Issue by womblep** [aasm/aasm#809]
Hi,
   It looks like there is a breaking change in the latest version 5.5.0 with callbacks.
I call transitions by calling them with arguments like this_event!(arg1, arg2). This has worked perfectly up to the latest change.
Now I get:
wrong number of arguments (given 1, expected 2) (ArgumentError)
2023-02-06T08:49:54.900982054Z /usr/src/app/my_aasm.rb:190:in `this_event'
2023-02-06T08:49:54.900988684Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/invokers/literal_invoker.rb:34:in `exec_subject'
2023-02-06T08:49:54.900992314Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/invokers/literal_invoker.rb:19:in `invoke_subject'
2023-02-06T08:49:54.900995604Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/invokers/base_invoker.rb:48:in `invoke'
2023-02-06T08:49:54.900998574Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/invoker.rb:85:in `invoke'
2023-02-06T08:49:54.901001844Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/transition.rb:75:in `invoke_callbacks_compatible_with_guard'
2023-02-06T08:49:54.901005324Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/transition.rb:49:in `execute'
2023-02-06T08:49:54.901007694Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/event.rb:158:in `block in _fire'
2023-02-06T08:49:54.901010154Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/event.rb:148:in `each'
2023-02-06T08:49:54.901012504Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/event.rb:148:in `_fire'
2023-02-06T08:49:54.901014034Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/core/event.rb:51:in `fire'
2023-02-06T08:49:54.901015474Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/aasm.rb:106:in `aasm_fire_event'
2023-02-06T08:49:54.901016814Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/persistence/orm.rb:132:in `block in aasm_fire_event'
2023-02-06T08:49:54.901018414Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/persistence/active_record_persistence.rb:105:in `block in aasm_transaction'
2023-02-06T08:49:54.901019934Z /usr/local/bundle/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
2023-02-06T08:49:54.901021564Z /usr/local/bundle/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
2023-02-06T08:49:54.901029124Z /usr/local/bundle/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
2023-02-06T08:49:54.901030844Z /usr/local/bundle/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
2023-02-06T08:49:54.901032584Z /usr/local/bundle/gems/activesupport-7.0.4.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
2023-02-06T08:49:54.901034614Z /usr/local/bundle/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
2023-02-06T08:49:54.901036104Z /usr/local/bundle/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
2023-02-06T08:49:54.901037544Z /usr/local/bundle/gems/activerecord-7.0.4.2/lib/active_record/transactions.rb:209:in `transaction'
2023-02-06T08:49:54.901038964Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/persistence/active_record_persistence.rb:103:in `aasm_transaction'
2023-02-06T08:49:54.901040384Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/persistence/orm.rb:131:in `aasm_fire_event'
2023-02-06T08:49:54.901041854Z /usr/local/bundle/gems/aasm-5.5.0/lib/aasm/base.rb:126:in `block in event'

**Comment by StragaSevera** [comment]
I have similar problems.

```
    event :close do
      before do |closed_at:|
        self.closed_at = closed_at
      end

      transitions from: :activated, to: :closed
    end
    # ...
    loan.close!(closed_at: Time.current)
```
results in:
`ArgumentError: missing keyword: :closed_at`

**Comment by tagliala** [comment]
Here it is a reduced test case for the second issue, affecting Ruby 3.2 only

```rb
# frozen_string_literal: true

require 'bundler/inline'

begin
  gemfile(true) do
    source 'https://rubygems.org'

    gem 'aasm', '5.4.0'
    gem 'activerecord'
    gem 'pg'
  end

  require 'aasm'
  require 'active_record'
  require 'logger'
rescue Gem::LoadError => e
  puts "\nMissing Dependency:\n#{e.backtrace.first} #{e.message}"
rescue LoadError => e
  puts "\nError:\n#{e.backtrace.first} #{e.message}"
  exit 1
end

ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'bench')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :loans, force: true do |t|
    t.string :status
    t.timestamp :closed_at
  end
end

class Loan < ActiveRecord::Base
  include AASM

  aasm(column: :status) do
    state :activated, initial: true
    state :closed

    event :close do
      before do |closed_at:|
        self.closed_at = closed_at
      end

      transitions from: :activated, to: :closed
    end
  end
end

loan = Loan.create!

loan.close! closed_at: Time.current
```
